const sequelize = require('../config/connection');
const { Comment } = require('../models');

const commentData = [
  {
    title: 'BIG BOLD COMMENT TITLE!!!!',
    body: 'This is a boring comment',
    tags: 1,
    user_id: 1,
    post_id: 1,

  },
  {
    title: 'This is a comment Numero Dos!',
    body: 'Kuzco sais NO TOUCHY TOUCHY!',
    tags: 1,
    user_id: 1,
    post_id: 1,

  },
  {
    title: 'not again!!',
    body: 'Squeek squeeker mc squeek squeeken!',
    tags: 1,
    user_id: 6,
    post_id: 1,

  },
  {
    title: 'Maybe this should be generated by user data and timestamps and such',
    body: 'blargidy blarg blarg.',
    tags: 1,
    user_id: 7,
    post_id: 1,

  },
  {
    title: 'hmmmmm.............',
    body: 'Insert test comment body Whatever shall be said here is required to stay here. I mean its not like the words can just up any walk away or anything....',
    tags: 1,
    user_id: 8,
    post_id: 1,

  },

];

const commentSeeds = () => Comment.bulkCreate(co);
module.exports = commentSeeds;